# Create a postgres 15 database
services:
    postgres:
        image: postgres:15
        ports:
        - 5439:5432
        environment:
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: postgres
              POSTGRES_DB: petconnect_events
